# Johnathan 'Qasparr' (Κασπάρρ) Monroe, Keeper of the Secret Treasure
# All Rights Reserved, Without Prejudice.  CashApp $axoneme
"""charts -- hand-rolled SVG charts. No dependencies, cross-platform.

    "The heavens declare the glory of God; and the firmament sheweth
     his handywork."
    -- Psalm 19:1

Hypothesis
----------
The ledger's numbers are not the knowledge; the *seeing* of them is.
A chart is the firmament showing its handywork -- the verdicts,
the traffic, the gate's own speed, made visible at a glance. And the
charting must itself be dependency-free: if the reports required a
plotting library, the gate would trade its cross-platform birthright
for one more install step that can fail on a bare machine.

Method
------
SVG, generated by string templating -- every chart is a single
``<svg>`` document the API serves as ``image/svg+xml``, embeddable
in any browser, dashboard, or report without JavaScript and without
a build step. The geometry is honest arithmetic: each bar's height
is its value divided by the series maximum, scaled to the plot
area; the baseline is drawn, not implied; labels are HTML-escaped
so a claim's text can never break the document (a chart must not
become an injection surface -- the gate's paranoia extends to its
own pictures).

Colors carry doctrine, not decoration: gold for TRVVTH, indigo for
UNRESOLVED, iron red for FALSEHOOD -- the alethic axis rendered as
a palette, so the eye learns the verdicts before the mind reads the
numbers. The layout constants (640x360 canvas, padding for axes and
titles) are module-level so the whole family of charts shares one
hand.

Observation
-----------
``bar_chart`` renders one series as vertical bars with value labels;
``timeline`` renders time-ordered values (day labels trimmed to
MM-DD for legibility); ``multi_series`` renders grouped bars with a
legend -- one group per benchmark name, one bar per run -- so the
gate's throughput across runs is comparable at a glance.
``verdict_chart`` is the canonical reading of the ledger: the three
verdicts in their doctrinal colors.

Result
------
Reports that any client can render, from a curl pipe to a wall
display, with nothing to install. The charts show the work; the
ledger beneath them proves it.

Fiction & film
--------------
"Do not try and bend the spoon -- that's impossible. Instead, only
try to realize the truth: there is no spoon." The chart does not
bend the data; it realizes there was never anything to bend -- the
shape was in the numbers all along. [The Wachowskis, The Matrix, 1999]
"""

from __future__ import annotations

import html

# The alethic palette: the verdicts as colors, so the eye learns the
# axis before the mind reads the numbers. Gold is TRVVTH -- what is
# proven shines; indigo is UNRESOLVED -- the held-open question, the
# night sky before the star is named; iron red is FALSEHOOD -- the
# color of the struck-through, the refused.
VERDICT_COLORS = {
    "TRVVTH": "#c9a227",      # gold
    "UNRESOLVED": "#3b3b6d",  # indigo
    "FALSEHOOD": "#a33327",   # iron red
}

# Ink on paper: the house style. Paper is warm (#faf8f2) rather than
# clinical white -- these are workings, not spreadsheets -- and the
# grid lines stay faint so the data, not the scaffolding, holds the eye.
INK = "#1a1a2e"
PAPER = "#faf8f2"
GRID = "#e3ddcf"

# One canvas for the whole family: 640x360, with padding reserved for
# the title block (top), the axis labels (bottom), and breathing room
# (left/right). Every chart function shares these, so the reports
# read as one document, not a collage.
_W = 640
_H = 360
_PAD_L = 56
_PAD_R = 20
_PAD_T = 44
_PAD_B = 48


def _frame(title: str, subtitle: str = "") -> tuple[list[str], int, int]:
    """Open the SVG document: canvas, paper, title, optional subtitle.

    Returns the list of document parts (to be joined at the end),
    plus the plot-area width and height -- the drawable region inside
    the padding. Every chart builds on this frame, so titles,
    typefaces (Georgia, the house serif), and the paper background
    are identical across the whole report family. The ``role="img"``
    and ``aria-label`` keep the chart legible to assistive
    technology: a picture the blind cannot see is a picture half
    drawn.
    """
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{_W}" height="{_H}"'
        f' role="img" aria-label="{html.escape(title)}">',
        f'<rect width="{_W}" height="{_H}" fill="{PAPER}"/>',
        f'<text x="{_W // 2}" y="26" text-anchor="middle"'
        f' font-family="Georgia,serif" font-size="17" fill="{INK}">'
        f'{html.escape(title)}</text>',
    ]
    if subtitle:
        parts.append(
            f'<text x="{_W // 2}" y="42" text-anchor="middle"'
            f' font-family="Georgia,serif" font-size="11" fill="#6b6b7d">'
            f'{html.escape(subtitle)}</text>')
    return parts, _W - _PAD_L - _PAD_R, _H - _PAD_T - _PAD_B


def bar_chart(title: str, items: list[tuple[str, float]],
              subtitle: str = "",
              colors: dict[str, str] | None = None) -> str:
    """One series as vertical bars: ``items`` is (label, value) pairs.

    The geometry: the tallest bar defines the scale (``top`` is the
    series maximum, floored at 1 so an all-zero series still draws a
    frame rather than dividing by zero); each bar's height is its
    value's fraction of ``top`` times the plot height. Bars are
    centered in equal slots, capped at 90px wide so a two-bar chart
    doesn't become two monoliths. Every bar carries its value as a
    label above it -- the chart shows the shape *and* states the
    number, because a picture that hides its data is decoration, not
    reportage. Labels are HTML-escaped: claim text reaching a chart
    must never become markup.
    """
    parts, pw, ph = _frame(title, subtitle)
    colors = colors or {}
    top = max([v for _, v in items] + [1])
    n = max(len(items), 1)
    slot = pw / n
    bw = min(slot * 0.62, 90)
    for i, (label, value) in enumerate(items):
        x = _PAD_L + slot * i + (slot - bw) / 2
        h = ph * (value / top) if top else 0
        y = _PAD_T + ph - h
        color = colors.get(label, "#3b3b6d")
        parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{bw:.1f}" height="{h:.1f}"'
            f' fill="{color}" rx="3"/>')
        parts.append(
            f'<text x="{x + bw / 2:.1f}" y="{y - 6:.1f}" text-anchor="middle"'
            f' font-size="12" font-family="Georgia,serif" fill="{INK}">'
            f'{value:g}</text>')
        parts.append(
            f'<text x="{x + bw / 2:.1f}" y="{_PAD_T + ph + 20:.1f}"'
            f' text-anchor="middle" font-size="11"'
            f' font-family="Georgia,serif" fill="#4a4a5e">'
            f'{html.escape(str(label))}</text>')
    # The baseline is drawn, not implied: the eye needs the ground
    # the bars stand on, or heights become guesses.
    parts.append(
        f'<line x1="{_PAD_L}" y1="{_PAD_T + ph}" x2="{_PAD_L + pw}"'
        f' y2="{_PAD_T + ph}" stroke="{INK}" stroke-width="1"/>')
    parts.append("</svg>")
    return "".join(parts)


def timeline(title: str, points: list[tuple[str, float]],
             subtitle: str = "", color: str = "#3b3b6d") -> str:
    """Time-ordered values as bars: ``points`` is (label, value) pairs.

    Built for days and for latency buckets alike. Day labels arrive
    as ISO dates ("2026-10-01") and are trimmed to MM-DD on the axis
    -- the year is context, not information, on a 30-day chart. When
    the series is long, every Nth label is drawn (``n // 10``) so the
    axis stays legible instead of becoming a smear; when it is short
    (12 or fewer), every label is drawn. The bars are drawn slightly
    transparent (opacity 0.85) -- a timeline is a rhythm, and rhythm
    reads better when the bars breathe.
    """
    parts, pw, ph = _frame(title, subtitle)
    top = max([v for _, v in points] + [1])
    n = max(len(points), 1)
    slot = pw / n
    bw = min(slot * 0.7, 40)
    for i, (label, value) in enumerate(points):
        x = _PAD_L + slot * i + (slot - bw) / 2
        h = ph * (value / top) if top else 0
        y = _PAD_T + ph - h
        parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{bw:.1f}" height="{h:.1f}"'
            f' fill="{color}" rx="2" opacity="0.85"/>')
        if n <= 12 or i % max(n // 10, 1) == 0:
            parts.append(
                f'<text x="{x + bw / 2:.1f}" y="{_PAD_T + ph + 18:.1f}"'
                f' text-anchor="middle" font-size="10"'
                f' font-family="Georgia,serif" fill="#4a4a5e">'
                f'{html.escape(str(label)[5:])}</text>')
    parts.append(
        f'<line x1="{_PAD_L}" y1="{_PAD_T + ph}" x2="{_PAD_L + pw}"'
        f' y2="{_PAD_T + ph}" stroke="{INK}" stroke-width="1"/>')
    parts.append("</svg>")
    return "".join(parts)


def multi_series(title: str, series: dict[str, list[tuple[str, float]]],
                 subtitle: str = "") -> str:
    """Grouped bars: series name -> [(label, value)], one group per label.

    This is the benchmark chart: each group is a benchmark
    ("weigh_quote", "admit_50_claims", ...), each bar within the
    group is a run, and the legend maps colors to run labels. Bars
    carry ``<title>`` tooltips with their exact values -- the grouped
    bar shows the comparison, the tooltip states the number, honoring
    the same show-and-tell rule as ``bar_chart``. The palette cycles
    through five house colors; a sixth series reuses the first, which
    is acceptable because the legend, not the hue alone, names each
    series.
    """
    parts, pw, ph = _frame(title, subtitle)
    labels: list[str] = []
    for pts in series.values():
        for label, _ in pts:
            if label not in labels:
                labels.append(label)
    lookup = {name: dict(pts) for name, pts in series.items()}
    top = max([v for pts in series.values() for _, v in pts] + [1])
    names = list(series.keys())
    palette = ["#c9a227", "#3b3b6d", "#a33327", "#2e7d6f", "#7d3b6d"]
    n_groups = max(len(labels), 1)
    slot = pw / n_groups
    bw = min(slot / max(len(names), 1) * 0.8, 46)
    for gi, label in enumerate(labels):
        for si, name in enumerate(names):
            value = lookup[name].get(label, 0)
            x = _PAD_L + slot * gi + (slot - bw * len(names)) / 2 + si * bw
            h = ph * (value / top) if top else 0
            y = _PAD_T + ph - h
            parts.append(
                f'<rect x="{x:.1f}" y="{y:.1f}" width="{bw:.1f}"'
                f' height="{h:.1f}" fill="{palette[si % len(palette)]}"'
                f' rx="2"><title>{html.escape(name)}: {value:g}</title></rect>')
        parts.append(
            f'<text x="{_PAD_L + slot * gi + slot / 2:.1f}"'
            f' y="{_PAD_T + ph + 20:.1f}" text-anchor="middle" font-size="11"'
            f' font-family="Georgia,serif" fill="#4a4a5e">'
            f'{html.escape(str(label))}</text>')
    # The legend, laid left to right beneath the plot: swatch, name,
    # swatch, name. Its x-position advances by the rendered width of
    # each name (7px per character, an approximation that holds for
    # the house serif at 11pt) plus fixed gaps.
    lx = _PAD_L
    for si, name in enumerate(names):
        parts.append(
            f'<rect x="{lx}" y="{_H - 16}" width="12" height="12"'
            f' fill="{palette[si % len(palette)]}"/>'
            f'<text x="{lx + 16}" y="{_H - 6}" font-size="11"'
            f' font-family="Georgia,serif" fill="{INK}">'
            f'{html.escape(name)}</text>')
        lx += 16 + len(name) * 7 + 18
    parts.append(
        f'<line x1="{_PAD_L}" y1="{_PAD_T + ph}" x2="{_PAD_L + pw}"'
        f' y2="{_PAD_T + ph}" stroke="{INK}" stroke-width="1"/>')
    parts.append("</svg>")
    return "".join(parts)


def verdict_chart(counts: dict[str, int]) -> str:
    """The canonical reading of the ledger: the three verdicts.

    The order is doctrinal, not alphabetical -- TRVVTH, UNRESOLVED,
    FALSEHOOD, the axis as the gate declares it -- and each bar wears
    its verdict's color from the alethic palette. This is the chart
    the API serves at /reports/charts/verdicts: the state of every
    word the gate has ever weighed, in one glance.
    """
    items = [(v, counts.get(v, 0)) for v in ("TRVVTH", "UNRESOLVED", "FALSEHOOD")]
    return bar_chart("Verdicts on the Alethic Axis", items,
                     subtitle="all workings weighed by this gate",
                     colors=VERDICT_COLORS)
